# Generated by Django 3.1.7 on 2021-04-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('Task', 'Task'), ('Event', 'Event'), ('Note', 'Note')], max_length=5, verbose_name='Key:')),
                ('details', models.CharField(max_length=50, verbose_name='Details:')),
            ],
        ),
        migrations.CreateModel(
            name='AddKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('Task', 'Task'), ('Event', 'Event'), ('Note', 'Note')], max_length=5, verbose_name='Key:')),
                ('description', models.CharField(max_length=50, verbose_name='Description:')),
            ],
        ),
        migrations.CreateModel(
            name='InputName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='image/', verbose_name='Select Profile Picture')),
                ('nickname', models.CharField(max_length=20, verbose_name='Update Nickname:')),
                ('bio', models.TextField(verbose_name='Update Bio:')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadProfile',
        ),
    ]
