# Generated by Django 3.1.7 on 2021-04-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1', '0002_auto_20210406_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddItemToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('Task', 'Task'), ('Event', 'Event'), ('Note', 'Note')], max_length=5, verbose_name='Key:')),
                ('details', models.CharField(max_length=50, verbose_name='Details:')),
            ],
        ),
        migrations.RenameModel(
            old_name='AddItem',
            new_name='AddItemThisWeek',
        ),
    ]
